/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectostablasdemultiplicardos;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author soniaa
 */
public class VentanaPrincipal extends javax.swing.JFrame implements FocusListener {
private int aciertos;
private GestionInformacion gestora=new GestionInformacion();
    
//comprueba si en el JtextField ct el usuario ha escrito la respuesta 
//correcta, si no ha sido así el fondo del ct pasará a colorearse en rojo y en
//eti se escribirá la respuesta correcta, y si la respuesta es correcta 
//se incrementará el número de aciertos, se coloreará el fondo de ct en verde y
//se borrará el texto de eti

private void colorearEinformar(JTextField ct, JLabel eti, int n){
 int numero=Integer.parseInt(ct.getText());
    
    if(!gestora.comprueba(numero, n)){
        ct.setBackground(Color.red);
        eti.setText(""+gestora.devuelveCorrecta(n));
        }
    else{
        ct.setBackground(Color.green);
        this.aciertos=aciertos+1;
     
 }
}
//comprueba que el usuario ha introducido un némero entre 2 y 9 
//(ambos incluidos) en ctNumeroTabla, si no lo ha hecho se genera una excepción
//con un mensaje adecuado
private void comprobarEntrada()throws Exception{
    String elNumero=ctNumeroDeTabla.getText();
if(!elNumero.matches("[2-9]{1}")){
    throw new Exception("inroduce un nuúmero adecuado");
}
}
//invoca al método setVisible de todos los paneles para que se visualicen o no, 
//        dependiendo de que el parámetro mostrar que recibe sea true o false
private void mostrarPaneles(boolean mostrar){
    jpPreguntas.setVisible(mostrar);
    jpRespuestas.setVisible(mostrar);
    jpRespuestasCorrectas.setVisible(mostrar);
    jpBotones.setVisible(mostrar);
}
//invoca al método mostrarPaneles para que los paneles NO se visualicen, 
//cambia el tamaño de la ventana a 400 x 200 píxeles, habilita ctNumeroTable y 
//bAceptar para que el usuario pueda introducir el número de tabla con el 
//que desea trabajar
private void pedirNumero(){
     mostrarPaneles(false);
    setSize(400, 200);
    ctNumeroDeTabla.setEnabled(true);
    bAceptar.setEnabled(true);
}

//Se deshabilitarán bAceptar y ctNumeroTabla para que el usuario no pueda introducir 
//un nuevo número de tabla y también se inhabilitará bBorrar para que no pueda borrar 
//la información que ya ha introducido en la tabla, se establecerá como tamaño de la
//ventana 400 pixeles de ancho por 500 de alto, se eliminarán los componentes actuales 
//de jpPreguntas, jpRespuestas y jpRespuestasCorrectas y se generarán los Jlabel,
//JTextField correctos y correspondientes a los paneles anteriores, por último, 
//se invocará al método mostrarPaneles para que los paneles se visualicen
private void visualizarPaneles(){
     bAceptar.setEnabled(false);
    ctNumeroDeTabla.setEnabled(false);
    bBorrar.setEnabled(false);
    setSize(400, 500);
    jpPreguntas.removeAll();
    jpRespuestas.removeAll();
    jpRespuestasCorrectas.removeAll();
    
    
    for(int x=0;x<10;x++){
        int numero=x+1;
        String mensaje="         "+this.ctNumeroDeTabla.getText()+"x"+numero;
        JLabel unLaberlPreguntas=new JLabel(mensaje);
        JLabel unLabel=new JLabel();
        JTextField unField= new JTextField();
        unField.addFocusListener(this);
        jpPreguntas.add(unLaberlPreguntas);
        jpRespuestas.add(unField);
        jpRespuestasCorrectas.add(unLabel);
        }
      mostrarPaneles(true);     
}


    public VentanaPrincipal() {
    initComponents();
    pedirNumero();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        ctNumeroDeTabla = new javax.swing.JTextField();
        jpPreguntas = new javax.swing.JPanel();
        jpRespuestas = new javax.swing.JPanel();
        jpRespuestasCorrectas = new javax.swing.JPanel();
        jpBotones = new javax.swing.JPanel();
        bComprobar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NÚMERO DE TABLA (2-9)");

        bAceptar.setText("ACEPTAR");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        jpPreguntas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpPreguntas.setLayout(new java.awt.GridLayout(10, 1));

        jpRespuestas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpRespuestas.setLayout(new java.awt.GridLayout(10, 1));

        jpRespuestasCorrectas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpRespuestasCorrectas.setLayout(new java.awt.GridLayout(10, 1));

        bComprobar.setText("COMPROBAR");
        bComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComprobarActionPerformed(evt);
            }
        });

        bBorrar.setText("BORRAR");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotonesLayout = new javax.swing.GroupLayout(jpBotones);
        jpBotones.setLayout(jpBotonesLayout);
        jpBotonesLayout.setHorizontalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bComprobar)
                .addGap(18, 18, 18)
                .addComponent(bBorrar)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpBotonesLayout.setVerticalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bComprobar)
                    .addComponent(bBorrar))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(bAceptar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jpPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpRespuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ctNumeroDeTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpRespuestasCorrectas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ctNumeroDeTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpRespuestas, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(jpPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpRespuestasCorrectas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComprobarActionPerformed
       //pone a 0 el valor del campo aciertos, invoca al método colorearEinformar 
        //con cada JTextfield del panel jpRespuestas, su correspondiente JLabel 
        //del panel jpRespuestasCorrectas y el número de línea de la tabla Cuando 
        //acaba de colorearEinformar, si aciertos es mayor o igual que 5 se habilitará el botón bBorrar
        this.aciertos=0;
        Component[] numerosCorrectos=jpRespuestasCorrectas.getComponents();
        Component[] numerosEscritos=jpRespuestas.getComponents();
        for(int x=0;x<10;x++){
            JLabel eti=(JLabel) numerosCorrectos[x];
            JTextField ct=(JTextField) numerosEscritos[x];
            this.colorearEinformar(ct, eti, x);
        }
        if(aciertos>=5){
          bBorrar.setEnabled(true);
        }
    }//GEN-LAST:event_bComprobarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        // Borra el texto de todos los JtextFiel del panel jpRespuestas y de todos 
        //los Jlabel del panel jpRespuestasCorrectas y después invoca al método pedirNumero()
        this.aciertos=0;
        Component[] numerosCorrectos=jpRespuestasCorrectas.getComponents();
        Component[] numerosEscritos=jpRespuestas.getComponents();
        for(int x=0;x<10;x++){
            JLabel eti=(JLabel) numerosCorrectos[x];
            JTextField ct=(JTextField) numerosEscritos[x];
            eti.setText("");
            ct.setText("");
            ct.setBackground(Color.white);
         }
        this.pedirNumero();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        // intenta ejecutar los métodos comprobarEntrada() y visualizarPanelkes(),
        //si al hacerlo se produce una exceptión, ésta se captura para dar el mensaje 
        //de la excepción, seleccionar el texto de ctNumeroTabla y darle el foco al mismo
        try {
            comprobarEntrada();
            visualizarPaneles();
            gestora.setTabla(Integer.parseInt(ctNumeroDeTabla.getText()));//envia 
            //el número que metes en ctNumeroTabla a la gestora
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, exception.getMessage());
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bComprobar;
    private javax.swing.JTextField ctNumeroDeTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpPreguntas;
    private javax.swing.JPanel jpRespuestas;
    private javax.swing.JPanel jpRespuestasCorrectas;
    // End of variables declaration//GEN-END:variables
//Colorea en blanco el JTextField al que el usuario ha dado el foco y elimina el 
    //texto de la JLabel correspondiente (si el usuario va a probar a poner la respuesta
    //correcta hacemos que deje de visualizarse dicha respuesta...para que se moleste 
    //en memorizarla al menos un momento)
  @Override
    public void focusGained(FocusEvent e) {
       Component[] numerosCorrectos=jpRespuestasCorrectas.getComponents();
        
        for(int x=0;x<10;x++){
            JLabel eti=(JLabel) numerosCorrectos[x];
            eti.setText("");
           
           
         }
        Component elComponente=e.getComponent();
        JTextField texto=(JTextField)elComponente;
        texto.selectAll();
        texto.setBackground(Color.white);
    }

    @Override
    public void focusLost(FocusEvent e) {
       }
}
    
